version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pg-dsw
    environment:
      POSTGRES_DB: empleados_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - dsw-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: empleados-app
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/empleados_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      APP_SECURITY_USER: admin
      APP_SECURITY_PASSWORD: admin123
    ports:
      - "8080:8080"
    networks:
      - dsw-net
    depends_on:
      postgres:
        condition: service_healthy

networks:
  dsw-net:
    driver: bridge
